### ISSUE TITLE
Twitter alternative frontend: DABR

### ISSUE THREAD

**Issue by fparri** [takomine/Open-source-alternatives#1]
It's still working, even though the projects seems to be halted:

https://dabr.co.uk
source: https://github.com/DavidCarrington/dabr

**Comment by takomine** [comment]
Personally, I wouldn't like to add any projects that have been abandoned for many years. It may have issues that will never be fixed.

Regardless. Is it still working properly? I might include it with a disclaimer that it is no longer being updated.

**Comment by fparri** [comment]
I see your point. I just pointed that out because it's the only Twitter lightweight web client still working almst flawlessly with older browsers and Opera Mini. Almost everything is working. The only thing which isn't is the direct messages area.

**Comment by takomine** [comment]
Okay. I suppose it will still be relevant to old devices (e.g., Symbian phones or old Android devices).

I'll add this with some disclaimers. Thanks.
