### ISSUE TITLE
Telegram Web Frontend: MPGram Web

### ISSUE THREAD

**Issue by fparri** [takomine/Open-source-alternatives#2]
Source: https://github.com/shinovon/mpgram-web
Link: https://mp.nnchan.ru/login.php

**Comment by takomine** [comment]
Is the website working on your end? I'm having a Cloudflare error when visiting the official instance.

**Comment by fparri** [comment]
Looks like they're having server problems right now. It was working yesterday.
I'm hosting a private instance of the code and it's working for me.

**Comment by takomine** [comment]
I'll add this to the list but exclude their official instance until it is properly working again. Thanks

**Comment by fparri** [comment]
Their official instance is up:

http://mp.nnchan.ru/

**Comment by takomine** [comment]
> Their official instance is up:
> 
> http://mp.nnchan.ru/

Updated now. Thanks.
